-- Database Updates for ViveCruit
-- Add billing and plan management columns to Users table

-- Add new columns to Users table
ALTER TABLE public.Users 
ADD COLUMN IF NOT EXISTS plan VARCHAR(50) DEFAULT 'Free',
ADD COLUMN IF NOT EXISTS plan_updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS payment_id VARCHAR(255),
ADD COLUMN IF NOT EXISTS order_id VARCHAR(255),
ADD COLUMN IF NOT EXISTS interviews_created INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS interviews_limit INTEGER DEFAULT 1;

-- Create payments table for tracking payment history
CREATE TABLE IF NOT EXISTS public.payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    user_email VARCHAR(255) NOT NULL,
    user_id VARCHAR(255),
    plan_name VARCHAR(50) NOT NULL,
    payment_id VARCHAR(255),
    order_id VARCHAR(255) NOT NULL,
    amount INTEGER NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'pending',
    payment_date TIMESTAMP WITH TIME ZONE DEFAULT now(),
    CONSTRAINT payments_pkey PRIMARY KEY (id)
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_users_plan ON public.Users(plan);
CREATE INDEX IF NOT EXISTS idx_users_interviews_created ON public.Users(interviews_created);
CREATE INDEX IF NOT EXISTS idx_payments_user_email ON public.payments(user_email);
CREATE INDEX IF NOT EXISTS idx_payments_status ON public.payments(status);
CREATE INDEX IF NOT EXISTS idx_payments_payment_date ON public.payments(payment_date);

-- Update existing users to have default values
UPDATE public.Users 
SET 
    plan = 'Free',
    interviews_created = 0,
    interviews_limit = 1
WHERE plan IS NULL OR interviews_created IS NULL OR interviews_limit IS NULL;

-- Add RLS policies if needed
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;

-- Grant permissions
GRANT ALL ON public.payments TO authenticated;
GRANT ALL ON public.payments TO service_role;

-- Verify the changes
SELECT 
    column_name, 
    data_type, 
    is_nullable, 
    column_default
FROM information_schema.columns 
WHERE table_name = 'Users' 
AND column_name IN ('plan', 'interviews_created', 'interviews_limit')
ORDER BY column_name;
