-- Fix Users table - Add missing billing columns
-- Run this in Supabase SQL Editor

-- Add missing billing columns to Users table
ALTER TABLE public."Users" 
ADD COLUMN IF NOT EXISTS plan VARCHAR(50) DEFAULT 'Free',
ADD COLUMN IF NOT EXISTS plan_updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS payment_id VARCHAR(255),
ADD COLUMN IF NOT EXISTS order_id VARCHAR(255),
ADD COLUMN IF NOT EXISTS interviews_created INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS interviews_limit INTEGER DEFAULT 1;

-- Update existing users with default values
UPDATE public."Users" 
SET 
    plan = COALESCE(plan, 'Free'),
    interviews_created = COALESCE(interviews_created, 0),
    interviews_limit = COALESCE(interviews_limit, 1),
    plan_updated_at = COALESCE(plan_updated_at, NOW())
WHERE 
    plan IS NULL 
    OR interviews_created IS NULL 
    OR interviews_limit IS NULL 
    OR plan_updated_at IS NULL;

-- Create payments table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    user_email VARCHAR(255) NOT NULL,
    user_id VARCHAR(255),
    plan_name VARCHAR(50) NOT NULL,
    payment_id VARCHAR(255),
    order_id VARCHAR(255) NOT NULL,
    amount INTEGER NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'pending',
    payment_date TIMESTAMP WITH TIME ZONE DEFAULT now(),
    CONSTRAINT payments_pkey PRIMARY KEY (id)
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_users_plan ON public."Users"(plan);
CREATE INDEX IF NOT EXISTS idx_users_interviews_created ON public."Users"(interviews_created);
CREATE INDEX IF NOT EXISTS idx_payments_user_email ON public.payments(user_email);
CREATE INDEX IF NOT EXISTS idx_payments_status ON public.payments(status);

-- Verify the changes
SELECT 
    column_name, 
    data_type, 
    is_nullable, 
    column_default
FROM information_schema.columns 
WHERE table_name = 'Users' 
AND column_name IN ('plan', 'interviews_created', 'interviews_limit')
ORDER BY column_name;

-- Show current users with their plan data
SELECT 
    email,
    plan,
    interviews_created,
    interviews_limit,
    credits
FROM public."Users" 
ORDER BY created_at DESC;
