apiVersion: v1
kind: Namespace
metadata:
  name: 2401096
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: interview-questions-deployment
  namespace: 2401096
spec:
  replicas: 2   # run 2 pods for better availability
  selector:
    matchLabels:
      app: interview-questions
  template:
    metadata:
      labels:
        app: interview-questions
    spec:
      imagePullSecrets:
        - name: nexus-secret
      containers:
      - name: interview-questions-app
        image: 127.0.0.1:30085/my-repository/interview-questions-app:v1
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: production
---
apiVersion: v1
kind: Service
metadata:
  name: interview-questions-service
  namespace: 2401096
spec:
  selector:
    app: interview-questions
  ports:
    - protocol: TCP
      port: 3000       # Service port
      targetPort: 3000 # Container port
  type: ClusterIP
